
order-processing:
  variables:
    urls:
#      market-data-service: localhost:8080
      exchange-service: http://localhost:8085/api/v1/exchange/orders
      redis:
        topic: "pubsub:market-data"
        topic-ex2: "pubsub:market-data-ex2"

server:
  port: 9090

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  redis:
    port: "${REDIS_PORT}"
    host: "${REDIS_HOST}"
    password: "${REDIS_PASSWORD}"